### PR TITLE
Fix apiserver etcd-servers flag when self-hosting.

### LINKED ISSUE #372: Bootkube prematurely exits if scheduler/controller-manager lose leader-election
This is most easily surfaced when using self-hosted etcd - because there is a period of time when pivoting from boot-etcd to self-hosted etcd that the compiled-in control plane is no longer able to contact the etcd cluster (and therefore give up leader status).

When either the scheduler or controller-manager give up leadership it calls an `os.Exit()` which kills bootkube entirely - and the bootstrap process may not be complete (e.g. boot-etcd still running, or in another incomplete state).

One fix might to to just provide the bootkube api-server with the expected addresses of both etcd's (boot-etcd, and the self-hosted etcd service ip) when running `bootkube start`. For example: https://github.com/kubernetes-incubator/bootkube/blob/master/hack/multi-node/bootkube-up#L16

Another solution in the future might be to use static manifests for control plane components, such that if they exit they won't affect bootkube.

/cc @hongchaodeng @xiang90

### LINKED ISSUE #411: `bootkube start` should allow specifying multiple etcd-servers
The current flag `--etcd-server` only allows one etcd endpoint to be specified. However, we should allow multiple etcd nodes to be used, which would mitigate some issues during the self-hosted etcd pivot (see: https://github.com/kubernetes-incubator/bootkube/issues/372).

### PR DESCRIPTION
**Pull request by diegs**
This adds the self-hosted etcd cluster to the temporary control plane
config, which should hopefully mitigate situations where the control
plane loses contact with etcd during the boot-etcd -> self-hosted-etcd
pivot and gives up leader status as a result.

I also fixed the hack/single-node config to not start local etcd
when running with self-hosting.

Fixes #411.

### CODE REVIEW

**Comment by diegs** [comment]
Signed the CLA.

File: pkg/bootkube/parse.go [hunk 1]
```diff
@@ -91,6 +91,24 @@ func detectEtcdIP(assetDir string) (string, error) {
...
+	}
+	var service v1.Service
+	err = yaml.Unmarshal(b, &service)
+	if err != nil {
+		return "", fmt.Errorf("can't unmarshal %s: %v", path, err)
+	}
+	if numPorts := len(service.Spec.Ports); numPorts != 1 {
+		return "", fmt.Errorf("expected 1 etcd cluster port, found: %d", numPorts)
+	}
+	return fmt.Sprintf("http://%s:%d", service.Spec.ClusterIP, service.Spec.Ports[0]), nil
```
Comment (yifan-gu) [inline pkg/bootkube/parse.go]: Will there be `https` ?
/cc @aaronlevy @xiang90

Comment (xiang90) [inline pkg/bootkube/parse.go]: it will be. but not for now.

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by diegs** [comment]
Manually ran bootkube.selfetcd.destruct.reboot and bootkube.selfetcd.scale, both passed.

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
tests look good to me

**Comment by aaronlevy** [comment]
One random note - github will use "fixes X" in PR comment to auto-close the issue. In this case I think it fixes https://github.com/kubernetes-incubator/bootkube/issues/411 -- but lets leave https://github.com/kubernetes-incubator/bootkube/issues/372 open to track other possible cases this could still happen

**Comment by diegs** [comment]
@aaronlevy done

@pbx0 is looking at the tests I believe. I had to invoke them manually, rkbot isn't working for some reason.

**Comment by pbx0** [comment]
@aaron: looking into. At least there are still some failures happening as a result of container pulling freezing up, I'm working on reducing number of pulls per test run via quayctl which i'm hoping will bring tests in-line with what we are seeing when run locally which should help make any remaining flakes far more obvious.
