### PR TITLE
e2e: remove flaky checkpointer test

### LINKED ISSUE #816: Test flake in TestCheckpointer/UnscheduleCheckpointer
https://jenkins-kube-lifecycle.prod.coreos.systems/job/bootkube-pr-e2e-calico/243/console

```
[1094973.894078] golang[6]: === RUN   TestCheckpointer
[1094973.894593] golang[6]: === RUN   TestCheckpointer/UnscheduleCheckpointer
[1095623.597129] golang[6]: === RUN   TestCheckpointer/UnscheduleParent
[1095923.635633] golang[6]: --- FAIL: TestCheckpointer (949.74s)
[1095923.645399] golang[6]:     --- FAIL: TestCheckpointer/UnscheduleCheckpointer (649.70s)
[1095923.645627] golang[6]:     	checkpointer_test.go:131: Failed to verifyCheckpoint: should not find checkpoint "test-checkpointer" in "/etc/kubernetes/checkpoint-secrets/bootkube-e2e-58f3f1da-unschedulecheckpointer", error: <nil>, output: "test-checkpointer-m9vl9"
```

### PR DESCRIPTION
**Pull request by colemickens**
Unable to determine root cause. Disabling the test now to cut down on friction for other PRs. For now, fixes #816.

### CODE REVIEW

**Comment by rphillips** [comment]
what is your thought on calling t.Skip("Skipping: https://link to issue") to skip the test

File: e2e/checkpointer_test.go [hunk 1]
```diff
@@ -24,117 +24,9 @@ const (
...
 }
 
-// 1. Schedule a pod checkpointer on worker node.
-// 2. Schedule a test pod on worker node.
-// 3. Reboot the worker without starting the kubelet.
-// 4. Delete the checkpointer on API server.
-// 5. Reboot the masters without starting the kubelet.
-// 6. Start the worker kubelet, verify the checkpointer and the pod are still running as static pods.
-// 7. Start the master kubelets, verify the checkpointer is removed but the pod is still running.
-func testCheckpointerUnscheduleCheckpointer(t *testing.T) {
```
Comment (xiang90) [inline e2e/checkpointer_test.go]: can you do t.skip("skip is for now since XXX") instead of removing it completely? or we do want to remove this forever?

**Comment by colemickens** [comment]
I'm in favor of skipping the test, personally. I'm just used to hearing "it's in version control, remove it!". I'll switch it.

**Comment by dghubble** [comment]
Have you been able to reproduce the flake in a cluster you have access to / are running yourself? Any confidence that it occurs at a certain stage or its random? Would be good to capture what has been tried already.

File: e2e/checkpointer_test.go (hunk 1 above)
Comment (ericchiang) [reply e2e/checkpointer_test.go]: :+1: for skipping

File: e2e/checkpointer_test.go [hunk 2]
```diff
@@ -24,117 +24,9 @@ const (
...
-	enableGroup.Wait()
-
-	// Verify that the test-checkpointer is cleaned up but the daemonset is still running.
-	if err := verifyPod(c, "test-checkpointer", false); err != nil {
-		t.Fatalf("Failed to verifyPod: %s", err)
-	}
-	if err := verifyPod(c, "test-nginx", true); err != nil {
-		t.Fatalf("Failed to verifyPod: %s", err)
-	}
-	if err := verifyCheckpoint(c, testNS, "test-checkpointer", false, false); err != nil {
```
Comment (ericchiang) [inline e2e/checkpointer_test.go]: To answer @dghubble's comments. I think this is the part we've seen fail consistently. Maybe just skip this part?

**Comment by colemickens** [comment]
So, here's what I've found for this test:

1. I can't reproduce it locally. I'm using the same script the Jenkins box uses, I've only changed the AWS region.

2. It's hard to test, something very strange happens if you run this test in a cluster where the test has already been run. I didn't follow it all the way down the rabbit hole, but I've seen two things happen:
  * the test fails with:

```
    --- FAIL: TestCheckpointer/UnscheduleCheckpointer (357.70s)                                           │··········································································································
        checkpointer_test.go:74: Failed to verify checkpoint: unable to ls "/etc/kubernetes/checkpoint-sec│··········································································································
rets/bootkube-e2e-4e86b875-unschedulecheckpointer", error: Process exited with status 2                   │··········································································································
                stdout:                                                                                   │··········································································································
                stderr: ls: cannot access '/etc/kubernetes/checkpoint-secrets/bootkube-e2e-4e86b875-unsche│··········································································································
dulecheckpointer': No such file or directory             
```

* but 99% of the time, it just runs part of the test, then bails, and prints out that the test passed successfully


I'm going to update this PR with Eric's suggestion, only skipping the end of the test that normally causes problems, with a comment linking to this issue and PR.
