### PR TITLE
Wait for kube-system namespace before creating assets

### LINKED ISSUE #319: Ensure kube-system namespace exists prior to creating cluster assets
`bootkube start` tries to create manifests before creating the `kube-system` namespace  and fails and doesn't try again:

```
[  161.686903] bootkube[5]: E0218 00:45:40.109073       5 create.go:35] Error creating assets: [error when creating "/core/assets/manifests/kube-apiserver-nord-ca-certs-configmap.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-apiserver-podDisruptionBudget.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-apiserver-secret.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-apiserver.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-controller-manager-podDisruptionBudget.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-controller-manager-secret.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-controller-manager.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-dns-autoscalar.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-dns-deployment.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-dns-podDisruptionBudget.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-dns-svc.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-flannel-cfg.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-flannel.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-proxy.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-rescheduler.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-scheduler-podDisruptionBudget.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-scheduler.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube2iam-clusterrole.yaml": client: etcd member https://e
[  161.688216] bootkube[5]: tcd-t0.platform.prod.aws.cloud.nordstrom.net:2379 has no leader, error when creating "/core/assets/manifests/kubelet-clusterrole.yaml": client: etcd member https://etcd-t0.platform.prod.aws.cloud.nordstrom.net:2379 has no leader]
[  161.688450] bootkube[5]: Error creating assets: [error when creating "/core/assets/manifests/kube-apiserver-nord-ca-certs-configmap.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-apiserver-podDisruptionBudget.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-apiserver-secret.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-apiserver.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-controller-manager-podDisruptionBudget.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-controller-manager-secret.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-controller-manager.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-dns-autoscalar.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-dns-deployment.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-dns-podDisruptionBudget.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-dns-svc.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-flannel-cfg.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-flannel.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-proxy.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-rescheduler.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-scheduler-podDisruptionBudget.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube-scheduler.yaml": namespaces "kube-system" not found, error when creating "/core/assets/manifests/kube2iam-clusterrole.yaml": client: etcd member https://etcd-t0.platform.prod.aws.cloud.nordstrom.net
```

### PR DESCRIPTION
**Pull request by carolynvs**
Instead of trying to handle the NotFound error, check that the kube-system namespace exists before attempting to create assets.

This fixes #319.

### CODE REVIEW

**Comment by aaronlevy** [comment]
ok to test

**Comment by aaronlevy** [comment]
@pbx0 seems that rktbot is being a bit spammy

**Comment by pbx0** [comment]
The tests seem fine. Quay 404'd when running bootkube on the destruct test via rkt for whatever reason. I'll re-run them now. 

@aaron: I'm not sure how to solve the spam problem. We have 4 different jenkins jobs using the ghprb plugin, and even though only 1 automatically wants to run, all 4 want to spam the thread and I don't know how to turn it off without turning off those jobs yet.

**Comment by pbx0** [comment]
rktbot run tests

File: pkg/bootkube/create.go [hunk 1]
```diff
@@ -23,40 +23,34 @@ func CreateAssets(manifestDir string, timeout time.Duration) error {
...
-				if details.Name == api.NamespaceSystem && details.Kind == "namespaces" {
-					return false, nil // retry
-				}
-			}
-			UserOutput("\nError creating assets: %v\n", err)
-			UserOutput("\nNOTE: Bootkube failed to create some cluster assets. It is important that manifest errors are resolved and resubmitted to the apiserver.\n")
-			UserOutput("For example, after resolving issues: kubectl create -f <failed-manifest>\n\n")
-		}
-		return true, nil
+		return true, err
```
Comment (aaronlevy) [inline pkg/bootkube/create.go]: We weren't returning an error here before because there had been situations where an asset wasn't created - but it really wasn't a failure case, per-se (or you could actually recover it normally). An example of this was the dns service failed to be created because another service was assigned the service IP it was expecting to use.

The question was, should we let the cluster continue to boot - then let an admin resolve the issue (e.g. change the service IP of the conflicting service, and re-create the DNS service) -- VS -- just outright failing.

My inclination would be to keep the behavior the same for now, unless we have a good reason to change it - so either log the error here and return nil, or log in caller, but don't bubble it up further. No strong feelings for either.

Comment (aaronlevy) [inline pkg/bootkube/create.go]: Also - given that this is subtle behavior - it might make sense to add a comment here if we do keep this behavior.

Comment (carolynvs) [inline pkg/bootkube/create.go]: Thanks for the background! It wasn't my intent to change the behavior. I'll go back to returning nil and add a comment explaining why.

**Comment by carolynvs** [comment]
@aaronlevy I've update the error handling to go back to allowing boot to continue when asset creation fails, and left a comment explaining why we aren't bubbling up the error.
