### PR TITLE
error: SilenceErrors and tweak error output

### LINKED ISSUE #910: Duplicate error messages printed
There are duplicate error messages printed with certain etcd command-line arguments.

```
core@ip-10-0-42-175 ~ $ sudo ./bootkube recover --etcd-ca-path /etc/ssl/etcd/ca.crt --etcd-certificate-path /etc/ssl/etcd/client.crt  --recovery-dir recovery --etcd-servers=https://127.0.0.1:2379 --kubeconfig ./kubeconfig
Error: you must specify both --etcd-certificate-path, and --etcd-private-key-path
you must specify both --etcd-certificate-path, and --etcd-private-key-path
```

### PR DESCRIPTION
**Pull request by rphillips**
* Use SilenceErrors to suppress the double printing of errors

Fixes #910

### CODE REVIEW

File: cmd/bootkube/main.go [hunk 1]
```diff
@@ -13,9 +13,10 @@ import (
 
 var (
 	cmdRoot = &cobra.Command{
-		Use:   "bootkube",
-		Short: "Bootkube!",
-		Long:  "",
+		Use:           "bootkube",
+		Short:         "Bootkube!",
+		SilenceErrors: true,
```
Comment (ericchiang) [inline cmd/bootkube/main.go]: Add a comment? Does this work for subcommands too?

Comment (rphillips) [reply cmd/bootkube/main.go]: sure does... it chains.

Comment (rphillips) [reply cmd/bootkube/main.go]: added a comment as well.
